In [5]:

import numpy as np
arr=np.array([1,2,3,4,5])
#it is a general method and it is slow compared to vectorization mehtod
for i in arr:
    print(i**2,end=" ")
print()
#vectorization method is faster and does the work simultenously 
result=arr**2
print(result)

1 4 9 16 25 
[ 1  4  9 16 25]


Scalaing arrays without memory is called BroadCAsting

In [7]:
result=arr+10
print(result)

[11 12 13 14 15]


In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]

[[2 4 6]
 [5 7 9]]


Normalizing Data Using Broadcasting

In [9]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
