BuildInMathematicalFunctions

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
np.mean(arr)

np.float64(3.0)

In [2]:
np.var(arr)

np.float64(2.0)

In [3]:
np.std(arr)

np.float64(1.4142135623730951)

In [4]:
np.min(arr)


np.int64(1)

In [5]:
np.max(arr)

np.int64(5)

In [6]:
np.sum(arr)

np.int64(15)

In [7]:
np.median(arr)

np.float64(3.0)

In [8]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(3.0)

In [9]:
np.argmax(arr)

np.int64(4)

In [13]:
arr1=np.array([5,6,7,8,9])
np.corrcoef(arr,arr1)

array([[1., 1.],
       [1., 1.]])

In [14]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [15]:
np.diff(arr)

array([1, 1, 1, 1])

In [16]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

In [17]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [18]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [19]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])