In [1]:
import numpy as np
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [2]:
print(arr1)

[1 2 3 4]


In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [7]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
#Continous adding
np.arange(2,100,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [10]:
#evenly spacing 
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [15]:
arr_2d=np.array([[1,2,3],
              [4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [16]:
#Checking properties
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Size : ",arr.size)
print("Shape :",arr.shape)
print("Dimensions : ",arr.ndim)
print("Data Type : ",arr.dtype)

Size :  6
Shape : (2, 3)
Dimensions :  2
Data Type :  int64


In [17]:
#Changing Data Types (Explictt type)
myarr=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float32')
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [18]:
print(myarr.dtype)

float32


In [20]:
arr_to_int=myarr.astype(np.int32)
print(arr_to_int)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(myarr.dtype)

float32


In [22]:
print(arr_to_int.dtype)

int32


In [27]:
arr2=np.array([[23,4,5,],[3,4,5],[9,8,7],[6,5,4]])
print("Before Reshaped ")
print(arr2)
reshaped=arr2.reshape((3,4))
print("After Reshaped")
print(reshaped)

Before Reshaped 
[[23  4  5]
 [ 3  4  5]
 [ 9  8  7]
 [ 6  5  4]]
After Reshaped
[[23  4  5  3]
 [ 4  5  9  8]
 [ 7  6  5  4]]


In [29]:
flattened = arr2.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

[23  4  5  3  4  5  9  8  7  6  5  4]
