In [14]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

print(arr[0:-1])
print(arr[0:])
print(arr[-4:-1])

print(arr[::-1])

10
50
[10 20 30 40]
[10 20 30 40 50]
[20 30 40]
[50 40 30 20 10]


In [17]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=a[3:6]
print(b)
b[1]=24
print(b)
print(a)


[1 2 3 4 5 6 7 8 9]
[4 5 6 7]
[ 4 24  6  7]
[ 1  2  3  4 24  6  7  8  9]


In [18]:
#To avoid changes in a array use simply .copy

c=a[7:9].copy()
print(c)
c[1]=222
print(c)
print(a)

[8 9]
[  8 222]
[ 1  2  3  4 24  6  7  8  9]


In [19]:
#fancy indexing
idx=[0,1,4,6]
print(a[idx])

[ 1  2 24  7]


In [22]:
#Boolean MAsking
for i in a:
    if i%2==0:
        print(i,end=" ")

2 4 24 6 8 

#Exercise for Practice


In [24]:
#Create a 3×3 array filled with random numbers and print its shape.
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("shape : ",arr.shape)

shape :  (3, 3)


In [27]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.

arr1=np.array([1.1,2.2,3.3])
converted=arr1.astype(np.int32)
print(converted)

[1 2 3]


In [29]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr2=np.array([1, 2, 3, 4, 5, 6])
idx=[1,3,5]
print(arr2[idx])

[2 4 6]


In [30]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
arr3=np.array([1,2,3,4,5,6,7,8,9])
reshaped=arr3.reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
#Use boolean masking to filter numbers greater than 50 in an array.
arr3=np.array([122,22,33,343,335,63,17,58,19])
mask=arr3>50
print(arr3[mask])

[122 343 335  63  58]
