In [1]:
import numpy as np
arr=np.array([[1 ,2 ,3],
 [4 ,5 ,6],
 [7 ,8 ,9]])

np.sum(arr,axis=0)

array([12, 15, 18])

In [2]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [3]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [4]:
#3d array

arr3D=np.array([
    [[1,2,3],[4,5,6]],

    [[7,8,9],[10,11,12]]
    
])
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
print(arr3D[0,1,1:])

[5 6]


In [8]:
arr3D[1,1,:]=0
print(arr3D)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 0 0]]]
